---
version: '3'

services:
    api:
        restart: always
        environment:
            - FLASK_ENV=development
        volumes:
            - ./backend/api:/app
    websocket:
        volumes:
            - ./backend/websocket:/app
    adminer:
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT-8080}:${ADMINER_PORT-8080}
        depends_on:
            - db
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.development
        environment:
            NEXT_PUBLIC_API_HOST: ${API_URL-http://192.168.0.100:8000/api}
            NEXT_PUBLIC_WS_HOST: ${WS_URL-ws://192.168.0.100:8001}
            NEXT_PUBLIC_FRONTEND_HOST: ${FRONTEND_URL-http://192.168.0.100}
        volumes:
            - ./frontend:/app
