apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: websocket
  name: websocket
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 8001
  selector:
    io.kompose.service: websocket
status:
  loadBalancer: {}
